name: Generate and Publish ICS

on:
  schedule:
    - cron: '0 * * * *' # toutes les heures
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Create .env file
        run: |
          echo "MYK_USERNAME=${{ secrets.MYK_USERNAME }}" >> .env
          echo "MYK_PASSWORD=${{ secrets.MYK_PASSWORD }}" >> .env
          # ... toutes les autres variables secrets

      - name: Run global calendar script
        run: python edt_general_global.py

      - name: Run split groups script
        run: python edt_split_groups.py

      - name: Move ICS files to ics folder
        run: |
          mkdir -p ics
          mv *.ics ics/

      - name: Deploy ICS to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ou GH_PAGES_TOKEN si PAT
          publish_dir: ./ics
          publish_branch: gh-pages
